blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Q&A Forum
    url: https://github.com/warengonzaga/buymeacoffee.js/discussions/new?category=q-a
    about: Have a question? Let us know!
  - name: ğŸ§  Suggestions
    url: https://github.com/WarenGonzaga/buymeacoffee.js/discussions/new?category=brainstorm
    about: Have an idea or suggestion? Let us know!
  - name: ğŸ“š Documentation
    url: https://docs.warengonzaga.com/buymeacoffeejs
    about: Official Documentation for BuyMeaCoffeeJS
